version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn verify
  deploy:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: if [ -z "${CI_PULL_REQUEST}" ]; then mvn deploy -P deploy -s settings.xml; fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - deploy:
        filters:
          branches:
            only: master

# ask josh how to install missing dependency
# yml file is valid
# installed maven ran " mvn dependency:go-offline"  and got the same error as building locally. Command is wrong??? 
